= pyHash9

A Python module that produces an X13 hash from an input string.


== Rationale

PyHash9 is useful for chain linearization and third party toolchains.

This module is a pure C/C++ implementation of X13, so it is much faster
than a pure Python implementation would be.


== Usage

PyHash9 offers three functions that operate on a single `bytes` argument,
called `data` herein:

* `digest`: returns the X13 digest of `data` as little endian `bytes`
* `hash`: returns the X13 digest of `data` as big endian `bytes`
* `hash9`: returns the X13 digest of `data` as `bytes` in an ASCII
  encoded hex number

The rule of thumb is that the endianness of `digest` reflects
other digest functions that return byte data, such as those from
hashlib.

However, the endianness of `hash` and `hash9` reflects string representations
of byte data as numbers, because string representations of numbers are
big endian in that the most significant digit is the earliest in the string.
The representation of cryptographic digests as numbers is ubiquitous in
the cryptocurrency field, with block and transaction identifiers being
just two examples.


=== Examples

[source,python]
----
>>> import pyHash9
>>> pyHash9.digest(b"Why did they call it Hash9?").hex()
'314c8dbd325412d2c36411db867b49a73de2b54317d64fa46c70eb631fd7dd3b'
>>> pyHash9.hash(b"Why did they call it Hash9?").hex()
'3bddd71f63eb706ca44fd61743b5e23da7497b86db1164c3d2125432bd8d4c31'
>>> pyHash9.hash9(b"Why did they call it Hash9?")
b'3bddd71f63eb706ca44fd61743b5e23da7497b86db1164c3d2125432bd8d4c31'
>>> pyHash9.hash9(b"Why did they call it Hash9?").decode("ASCII")
'3bddd71f63eb706ca44fd61743b5e23da7497b86db1164c3d2125432bd8d4c31'
----

While these functions can take either python strings (`str`), or
python bytes (`bytes`), it is recommended to use bytes to avoid any
problems related to encodings.

For example, given an ASCII or UTF-8 string:

[source,python]
----
>>> message_string = "Why did they call it Hash9?"
>>> message_bytes = bytes(message_string, "UTF-8")
>>> pyHash9.hash9(message_bytes)
b'3bddd71f63eb706ca44fd61743b5e23da7497b86db1164c3d2125432bd8d4c31'
----


== Build & Installation

Building now uses CMake, so building and installing the python extension
should be as easy as:

[source,bash]
----
mkdir build
cd build
cmake ..
make
make install
----


=== Custom Python3 Installations

If you have a non-standard Python 3 installation, you can point to
it with the environment variable "`CUSTOM_PYTHON_PATH`".

For example were Python 3 installed to `/opt/local/`:

[source,bash]
----
mkdir build
cd build
PYINCDIR=/opt/local/include/python cmake ..
make
make install
----


=== Personal Use Installation

The simplest option for users who don't have admin privileges
is to put `pyHash9.so` in a directory pointed to by `PYTHONPATH`.

==== Linux

As a regular user, the best way to install pyHash9 is to add it to
your personal `site-packages` directory:

[source,bash]
----
PYV=$(python --version 2>&1 | awk '{print $2}' | cut -d. -f1,2)
mkdir -p "${HOME}/.local/lib/python${PYV}/site-packages"
cp pyHash9.so "${HOME}/.local/lib/python${PYV}/site-packages"
----

==== MacOs

The commands are similar to Linux except that macOS uses
the user's `/Library`:

[source,bash]
----
PYV=$(python --version 2>&1 | awk '{print $2}' | cut -d. -f1,2)
mkdir -p "${HOME}/Library/Python/${PYV}/lib/python/site-packages"
cp pyHash9.so "${HOME}/Library/Python/${PYV}/lib/python/site-packages"
----


== Copyright

Copyright (c) 2016-2024 Stealth R&D LLC
