#!/bin/bash

set -ex

# This shouldn't be in the Dockerfile or containers built from the same image
# will have the same credentials.
if [ ! -e "$HOME/.StealthCoin/StealthCoin.conf" ]; then
    mkdir -p $HOME/.StealthCoin

    echo "Creating StealthCoin.conf"

    # Seed a random password for JSON RPC server
    cat <<EOF > $HOME/.StealthCoin/StealthCoin.conf
disablewallet=${DISABLEWALLET:-1}
printtoconsole=${PRINTTOCONSOLE:-1}
rpcuser=${RPCUSER:-stealthcoinrpc}
rpcpassword=${RPCPASSWORD:-`dd if=/dev/urandom bs=33 count=1 2>/dev/null | base64`}
gen=0
server=1
EOF

fi

# Download and extract bootstrap file on first run
if [ ! -e "$HOME/.StealthCoin/bootstrap.dat" ]; then
	echo $(whoami)
	stealth_download_bootstrap
fi

cat $HOME/.StealthCoin/StealthCoin.conf

echo "Initialization completed successfully"
