#!/bin/bash

set -ex

# This shouldn't be in the Dockerfile or containers built from the same image
# will have the same credentials.
if [ ! -e "$HOME/.StealthCoin/StealthCoin.conf" ]; then
    mkdir -p $HOME/.StealthCoin

    echo "Creating StealthCoin.conf"

    # Seed a random password for JSON RPC server
    cat <<EOF > $HOME/.StealthCoin/StealthCoin.conf
disablewallet=${DISABLEWALLET:-1}
printtoconsole=${PRINTTOCONSOLE:-1}
rpcuser=${RPCUSER:-stealthcoinrpc}
rpcpassword=${RPCPASSWORD:-`dd if=/dev/urandom bs=33 count=1 2>/dev/null | base64`}
server=1
daemon=1
debug=0
debugnet=1
debugqpos=1
testnet=${TESTNET:-1}
EOF

fi

cat $HOME/.StealthCoin/StealthCoin.conf

echo "Initialization completed successfully"
