#######################################################################
##  Qt Project Include for Tor on MacOS
#######################################################################

INCLUDEPATH += \
    src/tor \
    src/tor/adapter

HEADERS += \
    src/tor/core/onion_ntor.h \
    src/tor/core/connection.h \
    src/tor/core/proto_ext_or.h \
    src/tor/core/sendme.h \
    src/tor/core/proto_socks.h \
    src/tor/core/ocirc_event.h \
    src/tor/core/conflux_sys.h \
    src/tor/core/conflux_util.h \
    src/tor/core/circuitmux.h \
    src/tor/core/dos_options_st.h \
    src/tor/core/or_handshake_state_st.h \
    src/tor/core/dos_sys.h \
    src/tor/core/mainloop.h \
    src/tor/core/channel.h \
    src/tor/core/or_handshake_certs_st.h \
    src/tor/core/onion_fast.h \
    src/tor/core/mainloop_sys.h \
    src/tor/core/cpath_build_state_st.h \
    src/tor/core/extend_info_st.h \
    src/tor/core/circuitstats.h \
    src/tor/core/status.h \
    src/tor/core/circuit_st.h \
    src/tor/core/proto_cell.h \
    src/tor/core/relay_crypto.h \
    src/tor/core/server_port_cfg_st.h \
    src/tor/core/entry_port_cfg_st.h \
    src/tor/core/connection_or.h \
    src/tor/core/var_cell_st.h \
    src/tor/core/socks_request_st.h \
    src/tor/core/or_periodic.h \
    src/tor/core/scheduler.h \
    src/tor/core/or_sys.h \
    src/tor/core/policies.h \
    src/tor/core/cpuworker.h \
    src/tor/core/proto_http.h \
    src/tor/core/addr_policy_st.h \
    src/tor/core/cell_queue_st.h \
    src/tor/core/congestion_control_common.h \
    src/tor/core/versions.h \
    src/tor/core/mainloop_pubsub.h \
    src/tor/core/onion_crypto.h \
    src/tor/core/relay.h \
    src/tor/core/crypt_path_st.h \
    src/tor/core/listener_connection_st.h \
    src/tor/core/proto_control0.h \
    src/tor/core/congestion_control_vegas.h \
    src/tor/core/conflux_params.h \
    src/tor/core/conflux_st.h \
    src/tor/core/conflux_pool.h \
    src/tor/core/onion_ntor_v3.h \
    src/tor/core/periodic.h \
    src/tor/core/circuitlist.h \
    src/tor/core/or.h \
    src/tor/core/or_connection_st.h \
    src/tor/core/circuitpadding_machines.h \
    src/tor/core/entry_connection_st.h \
    src/tor/core/onion.h \
    src/tor/core/edge_connection_st.h \
    src/tor/core/crypt_path.h \
    src/tor/core/congestion_control_st.h \
    src/tor/core/congestion_control_flow.h \
    src/tor/core/channeltls.h \
    src/tor/core/connection_st.h \
    src/tor/core/origin_circuit_st.h \
    src/tor/core/extendinfo.h \
    src/tor/core/trace_probes_circuit.h \
    src/tor/core/tor_version_st.h \
    src/tor/core/channelpadding.h \
    src/tor/core/proto_haproxy.h \
    src/tor/core/port_cfg_st.h \
    src/tor/core/circuitpadding.h \
    src/tor/core/hs_ntor.h \
    src/tor/core/circuitmux_ewma.h \
    src/tor/core/address_set.h \
    src/tor/core/circuituse.h \
    src/tor/core/mainloop_state_st.h \
    src/tor/core/command.h \
    src/tor/core/reasons.h \
    src/tor/core/connection_edge.h \
    src/tor/core/crypt_path_reference_st.h \
    src/tor/core/or_circuit_st.h \
    src/tor/core/conflux.h \
    src/tor/core/protover.h \
    src/tor/core/onion_tap.h \
    src/tor/core/dos_config.h \
    src/tor/core/trace_probes_cc.h \
    src/tor/core/dos.h \
    src/tor/core/orconn_event.h \
    src/tor/core/cell_st.h \
    src/tor/core/conflux_cell.h \
    src/tor/core/destroy_cell_queue_st.h \
    src/tor/core/circuitbuild.h \
    src/tor/core/netstatus.h \
    src/tor/core/relay_crypto_st.h \
    src/tor/core/half_edge_st.h \
    src/tor/app/subsysmgr.h \
    src/tor/app/or_state_st.h \
    src/tor/app/resolve_addr.h \
    src/tor/app/config.h \
    src/tor/app/ntmain.h \
    src/tor/app/or_options_st.h \
    src/tor/app/shutdown.h \
    src/tor/app/toronion_main.h \
    src/tor/app/tor_cmdline_mode.h \
    src/tor/app/statefile.h \
    src/tor/app/risky_options.h \
    src/tor/app/quiet_level.h \
    src/tor/ext/compat_blake2.h \
    src/tor/ext/tor_readpassphrase.h \
    src/tor/ext/byteorder.h \
    src/tor/ext/siphash.h \
    src/tor/ext/tinytest_macros.h \
    src/tor/ext/tinytest.h \
    src/tor/ext/tor_queue.h \
    src/tor/ext/ht.h \
    src/tor/ext/keccak-tiny/keccak-tiny.h \
    src/tor/ext/equix/hashx/include/hashx.h \
    src/tor/ext/equix/hashx/src/force_inline.h \
    src/tor/ext/equix/hashx/src/compiler.h \
    src/tor/ext/equix/hashx/src/siphash.h \
    src/tor/ext/equix/hashx/src/virtual_memory.h \
    src/tor/ext/equix/hashx/src/context.h \
    src/tor/ext/equix/hashx/src/toronion_blake2.h \
    src/tor/ext/equix/hashx/src/hashx_endian.h \
    src/tor/ext/equix/hashx/src/siphash_rng.h \
    src/tor/ext/equix/hashx/src/program.h \
    src/tor/ext/equix/hashx/src/instruction.h \
    src/tor/ext/equix/hashx/src/unreachable.h \
    src/tor/ext/equix/include/equix.h \
    src/tor/ext/equix/src/solver.h \
    src/tor/ext/equix/src/context.h \
    src/tor/ext/equix/src/solver_heap.h \
    src/tor/ext/timeouts/timeout-debug.h \
    src/tor/ext/timeouts/timeout.h \
    src/tor/ext/trunnel/trunnel-impl.h \
    src/tor/ext/trunnel/trunnel.h \
    src/tor/ext/ed25519/donna/ed25519-donna-64bit-x86-32bit.h \
    src/tor/ext/ed25519/donna/ed25519-donna-portable-identify.h \
    src/tor/ext/ed25519/donna/ed25519-randombytes.h \
    src/tor/ext/ed25519/donna/modm-donna-64bit.h \
    src/tor/ext/ed25519/donna/ed25519-donna-basepoint-table.h \
    src/tor/ext/ed25519/donna/modm-donna-32bit.h \
    src/tor/ext/ed25519/donna/ed25519-donna.h \
    src/tor/ext/ed25519/donna/ed25519-donna-64bit-tables.h \
    src/tor/ext/ed25519/donna/ed25519-donna-64bit-x86.h \
    src/tor/ext/ed25519/donna/ed25519-hash-custom.h \
    src/tor/ext/ed25519/donna/ed25519-hash.h \
    src/tor/ext/ed25519/donna/ed25519-donna-64bit-sse2.h \
    src/tor/ext/ed25519/donna/curve25519-donna-32bit.h \
    src/tor/ext/ed25519/donna/curve25519-donna-sse2.h \
    src/tor/ext/ed25519/donna/ed25519-donna-32bit-sse2.h \
    src/tor/ext/ed25519/donna/ed25519_donna_tor.h \
    src/tor/ext/ed25519/donna/curve25519-donna-64bit.h \
    src/tor/ext/ed25519/donna/ed25519-donna-impl-base.h \
    src/tor/ext/ed25519/donna/regression.h \
    src/tor/ext/ed25519/donna/ed25519-donna-portable.h \
    src/tor/ext/ed25519/donna/ed25519-donna-32bit-tables.h \
    src/tor/ext/ed25519/donna/test-ticks.h \
    src/tor/ext/ed25519/donna/ed25519-randombytes-custom.h \
    src/tor/ext/ed25519/donna/curve25519-donna-helpers.h \
    src/tor/ext/ed25519/donna/ed25519.h \
    src/tor/ext/ed25519/donna/ed25519-donna-impl-sse2.h \
    src/tor/ext/ed25519/donna/ed25519-donna-batchverify.h \
    src/tor/ext/ed25519/ref10/ed25519_ref10.h \
    src/tor/ext/ed25519/ref10/sqrtm1.h \
    src/tor/ext/ed25519/ref10/crypto_uint32.h \
    src/tor/ext/ed25519/ref10/crypto_hash_sha512.h \
    src/tor/ext/ed25519/ref10/ge_sub.h \
    src/tor/ext/ed25519/ref10/pow225521.h \
    src/tor/ext/ed25519/ref10/ge_add.h \
    src/tor/ext/ed25519/ref10/randombytes.h \
    src/tor/ext/ed25519/ref10/crypto_int32.h \
    src/tor/ext/ed25519/ref10/crypto_sign.h \
    src/tor/ext/ed25519/ref10/crypto_verify_32.h \
    src/tor/ext/ed25519/ref10/d2.h \
    src/tor/ext/ed25519/ref10/api.h \
    src/tor/ext/ed25519/ref10/crypto_int64.h \
    src/tor/ext/ed25519/ref10/ge_madd.h \
    src/tor/ext/ed25519/ref10/ge_msub.h \
    src/tor/ext/ed25519/ref10/crypto_uint64.h \
    src/tor/ext/ed25519/ref10/fe.h \
    src/tor/ext/ed25519/ref10/pow22523.h \
    src/tor/ext/ed25519/ref10/ge_p2_dbl.h \
    src/tor/ext/ed25519/ref10/d.h \
    src/tor/ext/ed25519/ref10/sc.h \
    src/tor/ext/ed25519/ref10/ge.h \
    src/tor/ext/ed25519/ref10/base2.h \
    src/tor/ext/ed25519/ref10/base.h \
    src/tor/trunnel/flow_control_cells.h \
    src/tor/trunnel/trunnel-local.h \
    src/tor/trunnel/congestion_control.h \
    src/tor/trunnel/sendme_cell.h \
    src/tor/trunnel/circpad_negotiation.h \
    src/tor/trunnel/channelpadding_negotiation.h \
    src/tor/trunnel/pwbox.h \
    src/tor/trunnel/netinfo.h \
    src/tor/trunnel/link_handshake.h \
    src/tor/trunnel/cell_introduce1.h \
    src/tor/trunnel/cell_rendezvous.h \
    src/tor/trunnel/ed25519_cert.h \
    src/tor/trunnel/cell_establish_intro.h \
    src/tor/trunnel/extension.h \
    src/tor/trunnel/conflux.h \
    src/tor/trunnel/socks5.h \
    src/tor/lib/logging_types.h \
    src/tor/lib/time.h \
    src/tor/lib/timers.h \
    src/tor/lib/buffers_net.h \
    src/tor/lib/nettypes.h \
    src/tor/lib/compress_lzma.h \
    src/tor/lib/usdt.h \
    src/tor/lib/crypto_util.h \
    src/tor/lib/tortls_sys.h \
    src/tor/lib/git_revision.h \
    src/tor/lib/inaddr.h \
    src/tor/lib/handles.h \
    src/tor/lib/token_bucket.h \
    src/tor/lib/env.h \
    src/tor/lib/namemap_st.h \
    src/tor/lib/bitarray.h \
    src/tor/lib/crypto_rand.h \
    src/tor/lib/buffers_tls.h \
    src/tor/lib/pidfile.h \
    src/tor/lib/confmgt.h \
    src/tor/lib/kvline.h \
    src/tor/lib/approx_time.h \
    src/tor/lib/winlib.h \
    src/tor/lib/setuid.h \
    src/tor/lib/crypto_digest.h \
    src/tor/lib/pubsub_build.h \
    src/tor/lib/x25519_sizes.h \
    src/tor/lib/addsub.h \
    src/tor/lib/pubsub_builder_st.h \
    src/tor/lib/binascii.h \
    src/tor/lib/compat_ctype.h \
    src/tor/lib/pubsub_connect.h \
    src/tor/lib/debug.h \
    src/tor/lib/testsupport.h \
    src/tor/lib/getpass.h \
    src/tor/lib/toronion_cmp.h \
    src/tor/lib/socketpair.h \
    src/tor/lib/malloc.h \
    src/tor/lib/crypto_cipher.h \
    src/tor/lib/compress_none.h \
    src/tor/lib/uname.h \
    src/tor/lib/laplace.h \
    src/tor/lib/subsys.h \
    src/tor/lib/prometheus.h \
    src/tor/lib/msgtypes.h \
    src/tor/lib/tortls_st.h \
    src/tor/lib/compat_openssl.h \
    src/tor/lib/bloomfilt.h \
    src/tor/lib/unitparse.h \
    src/tor/lib/crypto_ed25519.h \
    src/tor/lib/meminfo.h \
    src/tor/lib/map.h \
    src/tor/lib/process_win32.h \
    src/tor/lib/ctassert.h \
    src/tor/lib/daemon.h \
    src/tor/lib/waitpid.h \
    src/tor/lib/typedvar.h \
    src/tor/lib/backtrace.h \
    src/tor/lib/time_fmt.h \
    src/tor/lib/path.h \
    src/tor/lib/keyval.h \
    src/tor/lib/util_bug.h \
    src/tor/lib/confline.h \
    src/tor/lib/toronion_conftypes.h \
    src/tor/lib/geoip.h \
    src/tor/lib/restrict.h \
    src/tor/lib/smartlist.h \
    src/tor/lib/util_string.h \
    src/tor/lib/address.h \
    src/tor/lib/events.h \
    src/tor/lib/process_unix.h \
    src/tor/lib/evloop_sys.h \
    src/tor/lib/lockfile.h \
    src/tor/lib/workqueue.h \
    src/tor/lib/compat_string.h \
    src/tor/lib/pubsub.h \
    src/tor/lib/pubsub_macros.h \
    src/tor/lib/metrics_store_entry.h \
    src/tor/lib/toronion_x509.h \
    src/tor/lib/crypto_init.h \
    src/tor/lib/threads.h \
    src/tor/lib/crypto_options_st.h \
    src/tor/lib/torversion.h \
    src/tor/lib/crypto_openssl_mgt.h \
    src/tor/lib/dispatch_cfg.h \
    src/tor/lib/alertsock.h \
    src/tor/lib/tortls_internal.h \
    src/tor/lib/compat_mutex.h \
    src/tor/lib/crypto_curve25519.h \
    src/tor/lib/weakrng.h \
    src/tor/lib/trace_sys.h \
    src/tor/lib/type_defs.h \
    src/tor/lib/userdb.h \
    src/tor/lib/smartlist_core.h \
    src/tor/lib/pubsub_flags.h \
    src/tor/lib/dh_sizes.h \
    src/tor/lib/cstring.h \
    src/tor/lib/x509_internal.h \
    src/tor/lib/toronion_pem.h \
    src/tor/lib/compat_libevent.h \
    src/tor/lib/namemap.h \
    src/tor/lib/tortls.h \
    src/tor/lib/country.h \
    src/tor/lib/scanf.h \
    src/tor/lib/crypto_format.h \
    src/tor/lib/fdio.h \
    src/tor/lib/process_sys.h \
    src/tor/lib/log_sys.h \
    src/tor/lib/dispatch_st.h \
    src/tor/lib/tvdiff.h \
    src/tor/lib/printf.h \
    src/tor/lib/timeval.h \
    src/tor/lib/crypto_dh.h \
    src/tor/lib/confmacros.h \
    src/tor/lib/order.h \
    src/tor/lib/conftesting.h \
    src/tor/lib/parse_int.h \
    src/tor/lib/memarea.h \
    src/tor/lib/crypto_ope.h \
    src/tor/lib/log.h \
    src/tor/lib/prob_distr.h \
    src/tor/lib/procmon.h \
    src/tor/lib/compress.h \
    src/tor/lib/metrics_common.h \
    src/tor/lib/gethostname.h \
    src/tor/lib/logic.h \
    src/tor/lib/structvar.h \
    src/tor/lib/lttng.h \
    src/tor/lib/bytes.h \
    src/tor/lib/compress_zlib.h \
    src/tor/lib/torerr.h \
    src/tor/lib/escape.h \
    src/tor/lib/conffile.h \
    src/tor/lib/var_type_def_st.h \
    src/tor/lib/crypto_rsa.h \
    src/tor/lib/smartlist_foreach.h \
    src/tor/lib/tor_gettimeofday.h \
    src/tor/lib/dispatch.h \
    src/tor/lib/compress_sys.h \
    src/tor/lib/process.h \
    src/tor/lib/confdecl.h \
    src/tor/lib/compat_time.h \
    src/tor/lib/wallclock_sys.h \
    src/tor/lib/fp.h \
    src/tor/lib/smartlist_split.h \
    src/tor/lib/thread_sys.h \
    src/tor/lib/torerr_sys.h \
    src/tor/lib/compat_compiler.h \
    src/tor/lib/numcpus.h \
    src/tor/lib/dispatch_cfg_st.h \
    src/tor/lib/resolve.h \
    src/tor/lib/winprocess_sys.h \
    src/tor/lib/torint.h \
    src/tor/lib/crypto_sys.h \
    src/tor/lib/pub_binding_st.h \
    src/tor/lib/libc.h \
    src/tor/lib/map_anon.h \
    src/tor/lib/mmap.h \
    src/tor/lib/network_sys.h \
    src/tor/lib/files.h \
    src/tor/lib/compress_zstd.h \
    src/tor/lib/socks5_status.h \
    src/tor/lib/crypto_pwbox.h \
    src/tor/lib/win32err.h \
    src/tor/lib/pubsub_publish.h \
    src/tor/lib/toronion_aes.h \
    src/tor/lib/buffers.h \
    src/tor/lib/inaddr_st.h \
    src/tor/lib/muldiv.h \
    src/tor/lib/qstring.h \
    src/tor/lib/ratelim.h \
    src/tor/lib/crypto_s2k.h \
    src/tor/lib/socket.h \
    src/tor/lib/stats.h \
    src/tor/lib/dir.h \
    src/tor/lib/di_ops.h \
    src/tor/lib/crypto_nss_mgt.h \
    src/tor/lib/digest_sizes.h \
    src/tor/lib/sandbox.h \
    src/tor/lib/dispatch_naming.h \
    src/tor/lib/tokpaste.h \
    src/tor/lib/bits.h \
    src/tor/lib/metrics_store.h \
    src/tor/lib/nss_countbytes.h \
    src/tor/lib/storagedir.h \
    src/tor/lib/crypto_hkdf.h \
    src/tor/lib/toronion_trace.h \
    src/tor/lib/time_sys.h \
    src/tor/lib/digestset.h \
    src/tor/lib/time_to_tm.h \
    src/tor/feature/routerlist_st.h \
    src/tor/feature/btrack_orconn.h \
    src/tor/feature/keypin.h \
    src/tor/feature/relay_periodic.h \
    src/tor/feature/routerinfo_st.h \
    src/tor/feature/relay_handshake.h \
    src/tor/feature/dirvote.h \
    src/tor/feature/hibernate.h \
    src/tor/feature/hs_ident.h \
    src/tor/feature/routerinfo.h \
    src/tor/feature/nodelist.h \
    src/tor/feature/tor_api_internal.h \
    src/tor/feature/btrack_sys.h \
    src/tor/feature/control.h \
    src/tor/feature/dirauth_sys.h \
    src/tor/feature/node_st.h \
    src/tor/feature/hs_opts_st.h \
    src/tor/feature/control_proto.h \
    src/tor/feature/predict_ports.h \
    src/tor/feature/voteflags.h \
    src/tor/feature/consdiffmgr.h \
    src/tor/feature/dircollate.h \
    src/tor/feature/selftest.h \
    src/tor/feature/bridges.h \
    src/tor/feature/ext_orport.h \
    src/tor/feature/nickname.h \
    src/tor/feature/control_cmd_args_st.h \
    src/tor/feature/entrynodes.h \
    src/tor/feature/fp_pair.h \
    src/tor/feature/policy_parse.h \
    src/tor/feature/routerlist.h \
    src/tor/feature/addressmap.h \
    src/tor/feature/dlstatus.h \
    src/tor/feature/authority_cert_st.h \
    src/tor/feature/replaycache.h \
    src/tor/feature/hs_metrics.h \
    src/tor/feature/dirserv.h \
    src/tor/feature/dirlist.h \
    src/tor/feature/nodefamily_st.h \
    src/tor/feature/routermode.h \
    src/tor/feature/relay_sys.h \
    src/tor/feature/microdesc.h \
    src/tor/feature/microdesc_st.h \
    src/tor/feature/circpathbias.h \
    src/tor/feature/node_select.h \
    src/tor/feature/networkstatus_voter_info_st.h \
    src/tor/feature/hs_stats.h \
    src/tor/feature/dirclient.h \
    src/tor/feature/shared_random_client.h \
    src/tor/feature/parsecommon.h \
    src/tor/feature/btrack_orconn_cevent.h \
    src/tor/feature/control_getinfo.h \
    src/tor/feature/dirclient_modes.h \
    src/tor/feature/dirauth_options_st.h \
    src/tor/feature/control_fmt.h \
    src/tor/feature/bwhist.h \
    src/tor/feature/loadkey.h \
    src/tor/feature/sigcommon.h \
    src/tor/feature/metrics_sys.h \
    src/tor/feature/vote_timing_st.h \
    src/tor/feature/hs_common.h \
    src/tor/feature/transports.h \
    src/tor/feature/recommend_pkg.h \
    src/tor/feature/relay_config.h \
    src/tor/feature/dir_server_st.h \
    src/tor/feature/describe.h \
    src/tor/feature/relay_find_addr.h \
    src/tor/feature/ns_parse.h \
    src/tor/feature/authcert.h \
    src/tor/feature/tor_api.h \
    src/tor/feature/control_connection_st.h \
    src/tor/feature/extrainfo_st.h \
    src/tor/feature/dsigs_parse.h \
    src/tor/feature/microdesc_parse.h \
    src/tor/feature/consdiff.h \
    src/tor/feature/circuitbuild_relay.h \
    src/tor/feature/directory.h \
    src/tor/feature/hs_pow.h \
    src/tor/feature/fmt_routerstatus.h \
    src/tor/feature/process_descs.h \
    src/tor/feature/control_hs.h \
    src/tor/feature/ns_detached_signatures_st.h \
    src/tor/feature/routerparse.h \
    src/tor/feature/hs_ob.h \
    src/tor/feature/hs_control.h \
    src/tor/feature/reachability.h \
    src/tor/feature/vote_routerstatus_st.h \
    src/tor/feature/rephist.h \
    src/tor/feature/onion_queue.h \
    src/tor/feature/dns_structs.h \
    src/tor/feature/voting_schedule.h \
    src/tor/feature/desc_store_st.h \
    src/tor/feature/hs_dos.h \
    src/tor/feature/conscache.h \
    src/tor/feature/rendmid.h \
    src/tor/feature/shared_random.h \
    src/tor/feature/shared_random_state.h \
    src/tor/feature/hsdir_index_st.h \
    src/tor/feature/transport_config.h \
    src/tor/feature/cached_dir_st.h \
    src/tor/feature/getinfo_geoip.h \
    src/tor/feature/routerstatus_st.h \
    src/tor/feature/networkstatus_sr_info_st.h \
    src/tor/feature/authmode.h \
    src/tor/feature/hs_service.h \
    src/tor/feature/dirauth_config.h \
    src/tor/feature/hs_descriptor.h \
    src/tor/feature/hs_circuit.h \
    src/tor/feature/bw_array_st.h \
    src/tor/feature/unparseable.h \
    src/tor/feature/btrack_circuit.h \
    src/tor/feature/signing.h \
    src/tor/feature/dircache.h \
    src/tor/feature/metrics.h \
    src/tor/feature/hs_sys.h \
    src/tor/feature/bridgeauth.h \
    src/tor/feature/routerset.h \
    src/tor/feature/networkstatus_st.h \
    src/tor/feature/torcert.h \
    src/tor/feature/dir_connection_st.h \
    src/tor/feature/bwauth.h \
    src/tor/feature/networkstatus.h \
    src/tor/feature/authcert_members.h \
    src/tor/feature/proxymode.h \
    src/tor/feature/nodefamily.h \
    src/tor/feature/routerkeys.h \
    src/tor/feature/hs_config.h \
    src/tor/feature/router.h \
    src/tor/feature/control_events.h \
    src/tor/feature/dns.h \
    src/tor/feature/hs_metrics_entry.h \
    src/tor/feature/geoip_stats.h \
    src/tor/feature/authcert_parse.h \
    src/tor/feature/dnsserv.h \
    src/tor/feature/signed_descriptor_st.h \
    src/tor/feature/hs_intropoint.h \
    src/tor/feature/document_signature_st.h \
    src/tor/feature/hs_cache.h \
    src/tor/feature/rendcommon.h \
    src/tor/feature/connstats.h \
    src/tor/feature/hs_cell.h \
    src/tor/feature/btrack_orconn_maps.h \
    src/tor/feature/control_cmd.h \
    src/tor/feature/control_auth.h \
    src/tor/feature/relay_metrics.h \
    src/tor/feature/hs_client.h \
    src/tor/feature/vote_microdesc_hash_st.h \
    src/tor/feature/guardfraction.h \
    src/tor/feature/download_status_st.h \
    src/tor/feature/hs_circuitmap.h \
    src/tor/feature/dirauth_periodic.h

SOURCES += \
    src/tor/core/circuitpadding_machines.c \
    src/tor/core/scheduler_kist.c \
    src/tor/core/periodic.c \
    src/tor/core/onion_ntor_v3.c \
    src/tor/core/circuitlist.c \
    src/tor/core/conflux_params.c \
    src/tor/core/conflux_pool.c \
    src/tor/core/trace_probes_circuit.c \
    src/tor/core/extendinfo.c \
    src/tor/core/hs_ntor.c \
    src/tor/core/circuitpadding.c \
    src/tor/core/proto_haproxy.c \
    src/tor/core/channelpadding.c \
    src/tor/core/crypt_path.c \
    src/tor/core/channeltls.c \
    src/tor/core/congestion_control_flow.c \
    src/tor/core/scheduler_vanilla.c \
    src/tor/core/onion.c \
    src/tor/core/conflux.c \
    src/tor/core/reasons.c \
    src/tor/core/command.c \
    src/tor/core/connection_edge.c \
    src/tor/core/circuituse.c \
    src/tor/core/address_set.c \
    src/tor/core/circuitmux_ewma.c \
    src/tor/core/netstatus.c \
    src/tor/core/circuitbuild.c \
    src/tor/core/conflux_cell.c \
    src/tor/core/orconn_event.c \
    src/tor/core/dos.c \
    src/tor/core/onion_tap.c \
    src/tor/core/protover.c \
    src/tor/core/trace_probes_cc.c \
    src/tor/core/dos_config.c \
    src/tor/core/channel.c \
    src/tor/core/mainloop.c \
    src/tor/core/dos_sys.c \
    src/tor/core/mainloop_sys.c \
    src/tor/core/onion_fast.c \
    src/tor/core/conflux_sys.c \
    src/tor/core/ocirc_event.c \
    src/tor/core/circuitmux.c \
    src/tor/core/conflux_util.c \
    src/tor/core/sendme.c \
    src/tor/core/proto_socks.c \
    src/tor/core/proto_ext_or.c \
    src/tor/core/onion_ntor.c \
    src/tor/core/connection.c \
    src/tor/core/connection_or.c \
    src/tor/core/relay_crypto.c \
    src/tor/core/proto_cell.c \
    src/tor/core/status.c \
    src/tor/core/circuitstats.c \
    src/tor/core/congestion_control_common.c \
    src/tor/core/cpuworker.c \
    src/tor/core/or_sys.c \
    src/tor/core/policies.c \
    src/tor/core/proto_http.c \
    src/tor/core/scheduler.c \
    src/tor/core/or_periodic.c \
    src/tor/core/proto_control0.c \
    src/tor/core/congestion_control_vegas.c \
    src/tor/core/relay.c \
    src/tor/core/onion_crypto.c \
    src/tor/core/mainloop_pubsub.c \
    src/tor/core/versions.c \
    src/tor/app/quiet_level.c \
    src/tor/app/subsystem_list.c \
    src/tor/app/tor_main.c \
    src/tor/app/subsysmgr.c \
    src/tor/app/ntmain.c \
    src/tor/app/shutdown.c \
    src/tor/app/resolve_addr.c \
    src/tor/app/config.c \
    src/tor/app/statefile.c \
    src/tor/app/toronion_main.c \
    src/tor/app/risky_options.c \
    src/tor/ext/readpassphrase.c \
    src/tor/ext/csiphash.c \
    src/tor/ext/keccak-tiny/keccak-tiny-unrolled.c \
    src/tor/ext/equix/hashx/src/blake2.c \
    src/tor/ext/equix/hashx/src/siphash_rng.c \
    src/tor/ext/equix/hashx/src/compiler_a64.c \
    src/tor/ext/equix/hashx/src/program.c \
    src/tor/ext/equix/hashx/src/hashx_context.c \
    src/tor/ext/equix/hashx/src/compiler_x86.c \
    src/tor/ext/equix/hashx/src/program_exec.c \
    src/tor/ext/equix/hashx/src/hashx.c \
    src/tor/ext/equix/hashx/src/compiler.c \
    src/tor/ext/equix/hashx/src/virtual_memory.c \
    src/tor/ext/equix/hashx/src/siphash.c \
    src/tor/ext/equix/src/equix.c \
    src/tor/ext/equix/src/context.c \
    src/tor/ext/equix/src/solver.c \
    src/tor/ext/trunnel/trunnel.c \
    src/tor/ext/curve25519_donna/curve25519-donna.c \
    src/tor/ext/ed25519/donna/ed25519_tor.c \
    src/tor/ext/ed25519/ref10/ge_msub.c \
    src/tor/ext/ed25519/ref10/fe_sq2.c \
    src/tor/ext/ed25519/ref10/fe_pow22523.c \
    src/tor/ext/ed25519/ref10/ge_madd.c \
    src/tor/ext/ed25519/ref10/ge_p3_tobytes.c \
    src/tor/ext/ed25519/ref10/ge_p3_dbl.c \
    src/tor/ext/ed25519/ref10/sc_muladd.c \
    src/tor/ext/ed25519/ref10/fe_sub.c \
    src/tor/ext/ed25519/ref10/fe_isnonzero.c \
    src/tor/ext/ed25519/ref10/fe_add.c \
    src/tor/ext/ed25519/ref10/ge_p1p1_to_p2.c \
    src/tor/ext/ed25519/ref10/fe_invert.c \
    src/tor/ext/ed25519/ref10/ge_tobytes.c \
    src/tor/ext/ed25519/ref10/ge_p2_0.c \
    src/tor/ext/ed25519/ref10/ge_p3_0.c \
    src/tor/ext/ed25519/ref10/fe_cmov.c \
    src/tor/ext/ed25519/ref10/ge_p2_dbl.c \
    src/tor/ext/ed25519/ref10/fe_1.c \
    src/tor/ext/ed25519/ref10/fe_copy.c \
    src/tor/ext/ed25519/ref10/sign.c \
    src/tor/ext/ed25519/ref10/keyconv.c \
    src/tor/ext/ed25519/ref10/fe_0.c \
    src/tor/ext/ed25519/ref10/fe_tobytes.c \
    src/tor/ext/ed25519/ref10/ge_p3_to_cached.c \
    src/tor/ext/ed25519/ref10/ge_add.c \
    src/tor/ext/ed25519/ref10/fe_neg.c \
    src/tor/ext/ed25519/ref10/ge_sub.c \
    src/tor/ext/ed25519/ref10/ge_scalarmult_base.c \
    src/tor/ext/ed25519/ref10/ge_double_scalarmult.c \
    src/tor/ext/ed25519/ref10/ge_precomp_0.c \
    src/tor/ext/ed25519/ref10/fe_frombytes.c \
    src/tor/ext/ed25519/ref10/fe_isnegative.c \
    src/tor/ext/ed25519/ref10/keypair.c \
    src/tor/ext/ed25519/ref10/ge_frombytes.c \
    src/tor/ext/ed25519/ref10/fe_sq.c \
    src/tor/ext/ed25519/ref10/open.c \
    src/tor/ext/ed25519/ref10/sc_reduce.c \
    src/tor/ext/ed25519/ref10/blinding.c \
    src/tor/ext/ed25519/ref10/ge_p1p1_to_p3.c \
    src/tor/ext/ed25519/ref10/fe_mul.c \
    src/tor/ext/ed25519/ref10/ge_p3_to_p2.c \
    src/tor/trunnel/link_handshake.c \
    src/tor/trunnel/ed25519_cert.c \
    src/tor/trunnel/extension.c \
    src/tor/trunnel/cell_establish_intro.c \
    src/tor/trunnel/cell_rendezvous.c \
    src/tor/trunnel/cell_introduce1.c \
    src/tor/trunnel/socks5.c \
    src/tor/trunnel/flow_control_cells.c \
    src/tor/trunnel/sendme_cell.c \
    src/tor/trunnel/congestion_control.c \
    src/tor/trunnel/circpad_negotiation.c \
    src/tor/trunnel/trunnel_conflux.c \
    src/tor/trunnel/netinfo.c \
    src/tor/trunnel/pwbox.c \
    src/tor/trunnel/channelpadding_negotiation.c \
    src/tor/lib/parse_int.c \
    src/tor/lib/procmon.c \
    src/tor/lib/prob_distr.c \
    src/tor/lib/crypto_ope.c \
    src/tor/lib/log.c \
    src/tor/lib/memarea.c \
    src/tor/lib/crypto_dh.c \
    src/tor/lib/printf.c \
    src/tor/lib/aes_openssl.c \
    src/tor/lib/order.c \
    src/tor/lib/trace.c \
    src/tor/lib/fdio.c \
    src/tor/lib/log_sys.c \
    src/tor/lib/process_sys.c \
    src/tor/lib/crypto_format.c \
    src/tor/lib/scanf.c \
    src/tor/lib/pubsub_check.c \
    src/tor/lib/tvdiff.c \
    src/tor/lib/compat_libevent.c \
    src/tor/lib/tortls.c \
    src/tor/lib/namemap.c \
    src/tor/lib/process.c \
    src/tor/lib/smartlist_split.c \
    src/tor/lib/fp.c \
    src/tor/lib/compat_time.c \
    src/tor/lib/crypto_rsa.c \
    src/tor/lib/tor_gettimeofday.c \
    src/tor/lib/structvar.c \
    src/tor/lib/conffile.c \
    src/tor/lib/torerr.c \
    src/tor/lib/escape.c \
    src/tor/lib/compress_zlib.c \
    src/tor/lib/compress.c \
    src/tor/lib/toronion_version.c \
    src/tor/lib/gethostname.c \
    src/tor/lib/metrics_common.c \
    src/tor/lib/network_sys.c \
    src/tor/lib/mmap.c \
    src/tor/lib/crypto_pwbox.c \
    src/tor/lib/compress_zstd.c \
    src/tor/lib/files.c \
    src/tor/lib/map_anon.c \
    src/tor/lib/libc.c \
    src/tor/lib/torerr_sys.c \
    src/tor/lib/dispatch_new.c \
    src/tor/lib/winprocess_sys.c \
    src/tor/lib/resolve.c \
    src/tor/lib/numcpus.c \
    src/tor/lib/crypto_hkdf.c \
    src/tor/lib/compat_pthreads.c \
    src/tor/lib/storagedir.c \
    src/tor/lib/time_to_tm.c \
    src/tor/lib/digestset.c \
    src/tor/lib/time_sys.c \
    src/tor/lib/dispatch_naming.c \
    src/tor/lib/metrics_store.c \
    src/tor/lib/freespace.c \
    src/tor/lib/bits.c \
    src/tor/lib/crypto_digest_openssl.c \
    src/tor/lib/socket.c \
    src/tor/lib/crypto_s2k.c \
    src/tor/lib/sandbox.c \
    src/tor/lib/di_ops.c \
    src/tor/lib/dir.c \
    src/tor/lib/muldiv.c \
    src/tor/lib/buffers.c \
    src/tor/lib/pubsub_publish.c \
    src/tor/lib/ratelim.c \
    src/tor/lib/qstring.c \
    src/tor/lib/compat_ctype.c \
    src/tor/lib/binascii.c \
    src/tor/lib/getpass.c \
    src/tor/lib/crypto_digest.c \
    src/tor/lib/pubsub_build.c \
    src/tor/lib/setuid.c \
    src/tor/lib/kvline.c \
    src/tor/lib/approx_time.c \
    src/tor/lib/addsub.c \
    src/tor/lib/token_bucket.c \
    src/tor/lib/compat_threads.c \
    src/tor/lib/inaddr.c \
    src/tor/lib/pidfile.c \
    src/tor/lib/confmgt.c \
    src/tor/lib/buffers_tls.c \
    src/tor/lib/crypto_rand.c \
    src/tor/lib/env.c \
    src/tor/lib/crypto_dh_openssl.c \
    src/tor/lib/pem.c \
    src/tor/lib/timers.c \
    src/tor/lib/buffers_net.c \
    src/tor/lib/git_revision.c \
    src/tor/lib/crypto_util.c \
    src/tor/lib/compress_lzma.c \
    src/tor/lib/backtrace.c \
    src/tor/lib/dispatch_core.c \
    src/tor/lib/typedvar.c \
    src/tor/lib/waitpid.c \
    src/tor/lib/daemon.c \
    src/tor/lib/confline.c \
    src/tor/lib/util_bug.c \
    src/tor/lib/keyval.c \
    src/tor/lib/time_fmt.c \
    src/tor/lib/path.c \
    src/tor/lib/crypto_ed25519.c \
    src/tor/lib/unitparse.c \
    src/tor/lib/map.c \
    src/tor/lib/meminfo.c \
    src/tor/lib/bloomfilt.c \
    src/tor/lib/prometheus.c \
    src/tor/lib/laplace.c \
    src/tor/lib/compress_none.c \
    src/tor/lib/uname.c \
    src/tor/lib/compat_mutex_pthreads.c \
    src/tor/lib/crypto_rand_fast.c \
    src/tor/lib/x509.c \
    src/tor/lib/crypto_cipher.c \
    src/tor/lib/malloc.c \
    src/tor/lib/socketpair.c \
    src/tor/lib/crypto_rand_numeric.c \
    src/tor/lib/evloop_sys.c \
    src/tor/lib/workqueue.c \
    src/tor/lib/lockfile.c \
    src/tor/lib/smartlist.c \
    src/tor/lib/process_unix.c \
    src/tor/lib/address.c \
    src/tor/lib/util_string.c \
    src/tor/lib/restrict.c \
    src/tor/lib/geoip.c \
    src/tor/lib/smartlist_core.c \
    src/tor/lib/userdb.c \
    src/tor/lib/type_defs.c \
    src/tor/lib/trace_sys.c \
    src/tor/lib/weakrng.c \
    src/tor/lib/x509_openssl.c \
    src/tor/lib/cstring.c \
    src/tor/lib/alertsock.c \
    src/tor/lib/dispatch_cfg.c \
    src/tor/lib/crypto_openssl_mgt.c \
    src/tor/lib/crypto_rsa_openssl.c \
    src/tor/lib/crypto_curve25519.c \
    src/tor/lib/compat_mutex.c \
    src/tor/lib/tortls_openssl.c \
    src/tor/lib/crypto_init.c \
    src/tor/lib/compress_buf.c \
    src/tor/lib/compat_string.c \
    src/tor/lib/metrics_store_entry.c \
    src/tor/feature/onion_queue.c \
    src/tor/feature/rephist.c \
    src/tor/feature/hs_dos.c \
    src/tor/feature/voting_schedule.c \
    src/tor/feature/control_hs.c \
    src/tor/feature/fmt_routerstatus.c \
    src/tor/feature/process_descs.c \
    src/tor/feature/hs_pow.c \
    src/tor/feature/circuitbuild_relay.c \
    src/tor/feature/directory.c \
    src/tor/feature/reachability.c \
    src/tor/feature/hs_control.c \
    src/tor/feature/hs_ob.c \
    src/tor/feature/routerparse.c \
    src/tor/feature/consdiff.c \
    src/tor/feature/microdesc_parse.c \
    src/tor/feature/dsigs_parse.c \
    src/tor/feature/ns_parse.c \
    src/tor/feature/relay_find_addr.c \
    src/tor/feature/authcert.c \
    src/tor/feature/tor_api.c \
    src/tor/feature/hs_descriptor.c \
    src/tor/feature/hs_circuit.c \
    src/tor/feature/hs_service.c \
    src/tor/feature/authmode.c \
    src/tor/feature/control_bootstrap.c \
    src/tor/feature/dirauth_config.c \
    src/tor/feature/getinfo_geoip.c \
    src/tor/feature/transport_config.c \
    src/tor/feature/shared_random.c \
    src/tor/feature/rendmid.c \
    src/tor/feature/conscache.c \
    src/tor/feature/shared_random_state.c \
    src/tor/feature/dnsserv.c \
    src/tor/feature/geoip_stats.c \
    src/tor/feature/authcert_parse.c \
    src/tor/feature/dns.c \
    src/tor/feature/hs_metrics_entry.c \
    src/tor/feature/router.c \
    src/tor/feature/hs_config.c \
    src/tor/feature/control_events.c \
    src/tor/feature/bwauth.c \
    src/tor/feature/torcert.c \
    src/tor/feature/routerkeys.c \
    src/tor/feature/nodefamily.c \
    src/tor/feature/proxymode.c \
    src/tor/feature/networkstatus.c \
    src/tor/feature/dircache.c \
    src/tor/feature/signing.c \
    src/tor/feature/btrack_circuit.c \
    src/tor/feature/unparseable.c \
    src/tor/feature/routerset.c \
    src/tor/feature/bridgeauth.c \
    src/tor/feature/hs_sys.c \
    src/tor/feature/metrics.c \
    src/tor/feature/hs_circuitmap.c \
    src/tor/feature/guardfraction.c \
    src/tor/feature/hs_client.c \
    src/tor/feature/dirauth_periodic.c \
    src/tor/feature/control_auth.c \
    src/tor/feature/control_cmd.c \
    src/tor/feature/btrack_orconn_maps.c \
    src/tor/feature/relay_metrics.c \
    src/tor/feature/rendcommon.c \
    src/tor/feature/hs_cache.c \
    src/tor/feature/hs_cell.c \
    src/tor/feature/btrack.c \
    src/tor/feature/connstats.c \
    src/tor/feature/hs_intropoint.c \
    src/tor/feature/control.c \
    src/tor/feature/dirauth_sys.c \
    src/tor/feature/nodelist.c \
    src/tor/feature/routerinfo.c \
    src/tor/feature/hibernate.c \
    src/tor/feature/hs_ident.c \
    src/tor/feature/dirvote.c \
    src/tor/feature/relay_periodic.c \
    src/tor/feature/relay_handshake.c \
    src/tor/feature/keypin.c \
    src/tor/feature/btrack_orconn.c \
    src/tor/feature/policy_parse.c \
    src/tor/feature/entrynodes.c \
    src/tor/feature/nickname.c \
    src/tor/feature/ext_orport.c \
    src/tor/feature/fp_pair.c \
    src/tor/feature/selftest.c \
    src/tor/feature/dircollate.c \
    src/tor/feature/consdiffmgr.c \
    src/tor/feature/bridges.c \
    src/tor/feature/control_proto.c \
    src/tor/feature/voteflags.c \
    src/tor/feature/predict_ports.c \
    src/tor/feature/circpathbias.c \
    src/tor/feature/microdesc.c \
    src/tor/feature/hs_stats.c \
    src/tor/feature/node_select.c \
    src/tor/feature/relay_sys.c \
    src/tor/feature/routermode.c \
    src/tor/feature/hs_metrics.c \
    src/tor/feature/dirlist.c \
    src/tor/feature/dirserv.c \
    src/tor/feature/addressmap.c \
    src/tor/feature/routerlist.c \
    src/tor/feature/replaycache.c \
    src/tor/feature/dlstatus.c \
    src/tor/feature/relay_config.c \
    src/tor/feature/describe.c \
    src/tor/feature/transports.c \
    src/tor/feature/hs_common.c \
    src/tor/feature/recommend_pkg.c \
    src/tor/feature/metrics_sys.c \
    src/tor/feature/sigcommon.c \
    src/tor/feature/loadkey.c \
    src/tor/feature/btrack_orconn_cevent.c \
    src/tor/feature/parsecommon.c \
    src/tor/feature/shared_random_client.c \
    src/tor/feature/dirclient.c \
    src/tor/feature/bwhist.c \
    src/tor/feature/control_fmt.c \
    src/tor/feature/control_getinfo.c \
    src/tor/feature/dirclient_modes.c
