#ifndef GENERIC_ORCONFIG_H_
#define GENERIC_ORCONFIG_H_

/** String describing which Tor Git repository version the source was
 * built from.  This string is generated by a bit of shell kludging in
 * src/or/include.am, and is usually right. Typically, it is the first
 * seven hex characters from the latest git commit when
 * downloaded/cloned.
 *
 * The file "micro-revision.i" is generally created by `make`.
 */

/*
const char tor_git_revision[] =
#ifndef _MSC_VER
#include "micro-revision.i"
#endif
  "";
 */


#if defined(_WIN32) || defined(_WIN64)
#  if defined(_WIN64)
#    define ARCH_IS_WINDOWS_64 1
#    include "orconfig-windows.h"
#  else
#    define ARCH_IS_WINDOWS_32 1
#    error "32 bit Windows is not supported."
#  endif
#elif defined(__darwin__) || defined(__APPLE__)
#  if defined(__aarch64__)
#    define ARCH_IS_APPLE_SILICON 1
#    include "orconfig-apple-silicon.h"
#  elif defined(__x86_64__)
#    define ARCH_IS_APPLE_INTEL 1
#    include "orconfig-apple-intel.h"
#  else
#    define ARCH_IS_APPLE_32 1
#    error "32 bit Macs are not supported."
#  endif
#elif defined(__LP64__) || defined(_LP64)
#  include "orconfig-linux.h"
#else
#  error "32 bit Linux is not supported."
#endif


/** Some essential variables that may not be defined in the
  * orconfig header files.
  */

#ifndef COMPILER
  /* Compiler name */
  #define COMPILER "unspecified"
#endif

#ifndef COMPILER_VENDOR
  /* Compiler vendor */
  #define COMPILER_VENDOR "unspecified"
#endif

#ifndef COMPILER_VERSION
  /* Compiler version */
  #define COMPILER_VERSION "unspecified"
#endif

#ifndef SHARE_DATADIR
  /* shared data dir */
  #define SHARE_DATADIR "/usr/local/share/tor"
#endif

#ifndef LOCALSTATEDIR
  /* home tor folder */
  #define LOCALSTATEDIR "."
#endif


#endif  // GENERIC_ORCONFIG_H_
